In [15]:
import numpy as np
import pandas as pd
import math

In [53]:
#Превратите датафрейм в квадрат с максимально возможной длиной стороны n, убрав отрицательные значения. 
#При необходимости удалите наименьшие значения. Порядок положительных чисел в результате должен 
#оставаться таким же, как и в оригинале.
#Подсказка:
#Шаг 1: Удалите отрицательные значения
#Шаг 2: Определите наибольший размер стороны квадрата n, который может получиться
#Шаг 3: Постройте квадрат со стороной n из ТОП n^2 наибольших значений
df = pd.DataFrame(np.random.RandomState(30).randint(-20, 50, 100).reshape(10,-1))
pos_val = df.values[df.values > 0] # значения неотрицательные
df.shape[0]
def num_to_remove(len_of_pos_vals = pos_val.shape[0]):
    size = np.sqrt(len_of_pos_vals)
    return len_of_pos_vals - math.floor(size) ** 2
num_to_remove()
l = pos_val.tolist()
for i in range(num_to_remove()): # удаление минимальных элементов до составления квадрата из оставшихся
    l.pop(l.index(min(l)))
    
print(np.array(l, float).reshape(int(np.sqrt(len(l))),int(np.sqrt(len(l)))))

[[17. 17. 25. 25. 33. 26. 21. 45.]
 [29. 25. 41. 15. 42. 26. 25. 44.]
 [42. 30. 13. 35. 38. 37. 24. 17.]
 [37. 19. 13. 27. 19. 16. 20. 34.]
 [49. 10. 29. 32. 24. 41. 14. 23.]
 [40. 31. 21. 36. 19. 13.  8. 38.]
 [25. 28. 35. 25. 11.  9. 24.  9.]
 [31. 35. 32. 41. 19. 10. 24. 27.]]


In [56]:
#Поменяйте местами строки 1 и 2
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df.rename(index = {1:2, 2:1}).sort_index())

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


In [71]:
#Измените порядок строк датафрейма таким образом, чтобы последние стали первыми, а первые последними (reverse).
df = pd.DataFrame(np.arange(25).reshape(5, -1))
new_df = df.rename(index = {i:len(df.index)-i - 1 for i in range(len(df.index))}).sort_index()
print(new_df.rename(index = {i:len(df.index)-i - 1 for i in range(len(df.index))}))

    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


In [81]:
#Выполните one-hot encoding для столбца А и добавьте результат к датафрейму
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
print(pd.get_dummies(df['a']).join(df.drop('a', axis = 1)))

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


In [136]:
#Определите имя столбца с наибольшим количеством строковых максимумов. 

df = pd.DataFrame(np.random.RandomState(30).randint(1,100, 40).reshape(10, -1))
df['max'] = df.max(axis=1)
nummax= [sum(df[c] == df['max']) for c in df.columns[:4]]
print(df)
print(nummax)
print(np.argmax(nummax))

    0   1   2   3  max
0  38  38  46  46   46
1  13  24   3  54   54
2  18  47   4  42   47
3   8  66  50  46   66
4  62  36  19  19   62
5  77  17   7  63   77
6  28  47  46  65   65
7  63  12  16  24   63
8  14  51  34  56   56
9  29  59  92  79   92
[3, 2, 2, 4]
3


In [137]:
#Создайте новый столбец таким образом, чтобы каждая строка содержала номер наиболее 
#удалённой строки-записи по евклидову расстоянию.
df = pd.DataFrame(np.random.RandomState(30).randint(1,100, 40).reshape(10, -1))
df

0   1   2   3
0  38  38  46  46
1  13  24   3  54
2  18  47   4  42
3   8  66  50  46
4  62  36  19  19
5  77  17   7  63
6  28  47  46  65
7  63  12  16  24
8  14  51  34  56
9  29  59  92  79