In [1]:
import numpy as np
import pandas as pd
import math

In [2]:
#Превратите датафрейм в квадрат с максимально возможной длиной стороны n, убрав отрицательные значения. 
#При необходимости удалите наименьшие значения. Порядок положительных чисел в результате должен 
#оставаться таким же, как и в оригинале.
#Подсказка:
#Шаг 1: Удалите отрицательные значения
#Шаг 2: Определите наибольший размер стороны квадрата n, который может получиться
#Шаг 3: Постройте квадрат со стороной n из ТОП n^2 наибольших значений
df = pd.DataFrame(np.random.RandomState(30).randint(-20, 50, 100).reshape(10,-1))
pos_val = df.values[df.values > 0] # значения неотрицательные
df.shape[0]
def num_to_remove(len_of_pos_vals = pos_val.shape[0]):
    size = np.sqrt(len_of_pos_vals)
    return len_of_pos_vals - math.floor(size) ** 2
num_to_remove()
l = pos_val.tolist()
for i in range(num_to_remove()): # удаление минимальных элементов до составления квадрата из оставшихся
    l.pop(l.index(min(l)))
    
print(np.array(l, float).reshape(int(np.sqrt(len(l))),int(np.sqrt(len(l)))))

[[17. 17. 25. 25. 33. 26. 21. 45.]
 [29. 25. 41. 15. 42. 26. 25. 44.]
 [42. 30. 13. 35. 38. 37. 24. 17.]
 [37. 19. 13. 27. 19. 16. 20. 34.]
 [49. 10. 29. 32. 24. 41. 14. 23.]
 [40. 31. 21. 36. 19. 13.  8. 38.]
 [25. 28. 35. 25. 11.  9. 24.  9.]
 [31. 35. 32. 41. 19. 10. 24. 27.]]


In [3]:
#Поменяйте местами строки 1 и 2
df = pd.DataFrame(np.arange(25).reshape(5, -1))
print(df.rename(index = {1:2, 2:1}).sort_index())

    0   1   2   3   4
0   0   1   2   3   4
1  10  11  12  13  14
2   5   6   7   8   9
3  15  16  17  18  19
4  20  21  22  23  24


In [4]:
#Измените порядок строк датафрейма таким образом, чтобы последние стали первыми, а первые последними (reverse).
df = pd.DataFrame(np.arange(25).reshape(5, -1))
new_df = df.rename(index = {i:len(df.index)-i - 1 for i in range(len(df.index))}).sort_index()
print(new_df.rename(index = {i:len(df.index)-i - 1 for i in range(len(df.index))}))

    0   1   2   3   4
4  20  21  22  23  24
3  15  16  17  18  19
2  10  11  12  13  14
1   5   6   7   8   9
0   0   1   2   3   4


In [5]:
#Выполните one-hot encoding для столбца А и добавьте результат к датафрейму
df = pd.DataFrame(np.arange(25).reshape(5,-1), columns=list('abcde'))
print(pd.get_dummies(df['a']).join(df.drop('a', axis = 1)))

   0  5  10  15  20   b   c   d   e
0  1  0   0   0   0   1   2   3   4
1  0  1   0   0   0   6   7   8   9
2  0  0   1   0   0  11  12  13  14
3  0  0   0   1   0  16  17  18  19
4  0  0   0   0   1  21  22  23  24


In [6]:
#Определите имя столбца с наибольшим количеством строковых максимумов. 

df = pd.DataFrame(np.random.RandomState(30).randint(1,100, 40).reshape(10, -1))
df['max'] = df.max(axis=1)
nummax= [sum(df[c] == df['max']) for c in df.columns[:4]]
print(df)
print(nummax)
print(np.argmax(nummax))

    0   1   2   3  max
0  38  38  46  46   46
1  13  24   3  54   54
2  18  47   4  42   47
3   8  66  50  46   66
4  62  36  19  19   62
5  77  17   7  63   77
6  28  47  46  65   65
7  63  12  16  24   63
8  14  51  34  56   56
9  29  59  92  79   92
[3, 2, 2, 4]
3


In [61]:
#Создайте новый столбец таким образом, чтобы каждая строка содержала номер наиболее 
#удалённой строки-записи по евклидову расстоянию.
df = pd.DataFrame(np.random.RandomState(30).randint(1,100, 40).reshape(10, -1))
def max_distance(df,num_str):
    other_indexes = df.index.to_list()
    other_indexes.pop(num_str)
    dist = dict()
    for i in other_indexes:
        dist[i] = np.sqrt(((df.iloc[[num_str]].values - df.iloc[[i]].values)** 2).sum())
    maxim = max(dist.values())
    for key, val in dist.items():
        if val == maxim:
            return key, round(maxim)
df['nearest_row'], df['dist'] = [max_distance(df, i)[0]  for  i in df.index], [max_distance(df, i)[1]  for  i in df.index]
#df['dist'] = [max_distance(df, i)[1] for  i in df.index]
print(df)


    0   1   2   3
0  38  38  46  46
1  13  24   3  54
2  18  47   4  42
3   8  66  50  46
4  62  36  19  19
5  77  17   7  63
6  28  47  46  65
7  63  12  16  24
8  14  51  34  56
9  29  59  92  79
52.28766584960549
47.54997371187496
41.23105625617661
45.14421336118285
61.41661013113635
23.280893453645632
51.81698563212646
31.448370387032774
61.04916051838878
    0   1   2   3  nearest_row  dist
0  38  38  46  46            5    61
1  13  24   3  54            9   100
2  18  47   4  42            9    97
3   8  66  50  46            5    96
4  62  36  19  19            9   103
5  77  17   7  63            9   107
6  28  47  46  65            7    71
7  63  12  16  24            9   110
8  14  51  34  56            5    77
9  29  59  92  79            7   110


In [41]:
#Определите максимально возможное значение корреляции каждого столбца по сравнению с другими столбцами датафрейма.
df = pd.DataFrame(np.random.RandomState(25).randint(1,100, 80).reshape(8, -1), columns=list('pqrstuvwxy'), 
                  index=list('abcdefgh'))
corr = abs(df.corr())
corr[np.isclose(corr, 1)]  = 0
print(corr)
#corr.apply(lambda x: 0 if any(x) == 1 else x, axis = 0)
print(corr.apply(lambda x: round(max(x), 2), axis = 0).values)

          p         q         r         s         t         u         v  \
p  0.000000  0.512107  0.767901  0.139413  0.052365  0.544037  0.335403   
q  0.512107  0.000000  0.209535  0.424986  0.013054  0.639377  0.142553   
r  0.767901  0.209535  0.000000  0.187936  0.295132  0.408626  0.171527   
s  0.139413  0.424986  0.187936  0.000000  0.152527  0.845489  0.606281   
t  0.052365  0.013054  0.295132  0.152527  0.000000  0.019302  0.319836   
u  0.544037  0.639377  0.408626  0.845489  0.019302  0.000000  0.210305   
v  0.335403  0.142553  0.171527  0.606281  0.319836  0.210305  0.000000   
w  0.666213  0.391215  0.083154  0.150114  0.619769  0.215764  0.430686   
x  0.036061  0.249027  0.433272  0.410009  0.440047  0.237842  0.308671   
y  0.113365  0.049830  0.013345  0.297120  0.114302  0.184201  0.621780   

          w         x         y  
p  0.666213  0.036061  0.113365  
q  0.391215  0.249027  0.049830  
r  0.083154  0.433272  0.013345  
s  0.150114  0.410009  0.297120  
t  0

In [45]:
#Определите отношение минимума к максимуму для каждой строки.
df = pd.DataFrame(np.random.RandomState(25).randint(1,100, 80).reshape(8, -1))
print(df.apply(lambda x: min(x) / max(x), axis = 1))

0    0.054945
1    0.022222
2    0.023529
3    0.022989
4    0.030303
5    0.032967
6    0.170455
7    0.164835
dtype: float64


In [60]:
#Создайте новый столбец penultimate (с англ. предпоследний), который имеет второе по величине 
#значение каждой строки датафрейма:
df = pd.DataFrame(np.random.RandomState(25).randint(1,100, 80).reshape(8, -1))
print(df.apply(second_max, axis = 1))
df['penultimate'] = df.apply(second_max, axis = 1)
def second_max(x):
    x = np.sort(x)
    return x[-2]
print(df)

0    63
1    89
2    74
3    86
4    93
5    85
6    84
7    89
dtype: int64
    0   1   2   3   4   5   6   7   8   9  penultimate
0   5  63  91  16  62  24  45  51   9  29           63
1   5  90  32  70   2  40   4  89  56   4           89
2  85  46   4   2  23  32  49  48  74  17           74
3  51  86  37  10  33  11  61  48   2  87           86
4  92  50  19  93  37  99  31  39   3   6           93
5  58  74  23  12   3  44  91  62  85  84           85
6  75  18  15  84  38  88  51  52  15  72           84
7  63  91  16  15  77  40  89  47  54  30           89


In [66]:
#Нормализуйте все столбцы датафрейма, вычитая среднее значение столбца и разделив на стандартное отклонение:
df = pd.DataFrame(np.random.RandomState(20).randint(1,100, 80).reshape(8, -1))
print(df.apply(lambda x: round((x - np.mean(x)) / x.std(),2), axis = 0))

0     1     2     3     4     5     6     7     8     9
0  1.47 -1.13  1.31 -0.59  1.38 -1.00 -1.27  0.98 -0.46  0.59
1 -0.23  1.07 -0.50  1.08  1.38 -0.47  1.03 -0.97  0.72 -1.08
2 -1.05  1.12 -1.62 -0.65 -0.69  1.07  0.12 -0.67 -1.02  0.68
3  1.02  0.12  0.72  1.02  0.50  1.67 -0.83 -1.17 -0.93  0.71
4 -0.71 -1.45  0.72 -0.92  0.12 -0.78 -1.34  1.11  1.55  0.23
5  0.89  0.50 -0.86 -0.10 -0.87  0.70  0.85 -0.71 -0.58  1.26
6 -0.26  0.58 -0.43  1.34 -0.95 -0.72  0.56  0.22 -0.46 -1.14
7 -1.14 -0.80  0.66 -1.18 -0.87 -0.47  0.89  1.21  1.19 -1.26